config/routes.rb
Commitboards::Application.routes.draw do

  post 'oauth/callback'  => 'oauths#callback'
  get  'oauth/callback'  => 'oauths#callback'
  get  'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider
  resource :session , only: [:new, :destroy]
  get 'session/new/:board_id' => 'sessions#new', as: :new_session_from_board

  resource :dashboard, only: :show

  scope :downloads do
    get 'capture'   => 'scripts#capture_script',                     as: 'capture_script'
    get 'bgcapture' => 'scripts#background_capture_script',          as: 'background_capture_script'
    get 'update_and_capture' => 'scripts#update_and_capture_script', as: 'update_and_capture_script'
    get 'imagesnap' => 'scripts#imagesnap',                          as: 'imagesnap'
    get 'version'   => 'scripts#version',                            as: 'version'
  end
  # need an alias for the version checking, since all the distributed scripts have a board url
  get ':board_id/version' => 'scripts#version'

  get 'install/:token' => 'scripts#install', as: 'install'
  # just an alias to the install script as client scripts for commitboards
  # have access to the board url. Then its easy to append /install/<token>
  get ':board_id/install/:token' => 'scripts#install'

  resources :boards, path: '/', only: [:show, :create] do
    resources :commits, only: [:create, :show] do
      resources :comments, only: [:create, :update]
    end
  end

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commit, counter_cache: true
  validates :user_id, :commit_id, presence: true
  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_login
  before_filter :load_board
  before_filter :load_commit
  respond_to :html, :json
  layout false

  def create
    @comment = @commit.comments.build comment_params.merge({ user: current_user })
    if @comment.save
      render '_comment'  
    else
      render nothing: true, status: 401
    end
  end

  def update
    @comment = @commit.comments.find(params[:id])
    return render nothing: true, status: 401 unless @comment.user  == current_user
    if @comment.update(comment_params)
      render '_comment'
    else
      render nothing: true, status: 401
    end
  end

private
  def comment_params
    params.require(:comment).permit(:body)
  end


  def load_board
    @board = Board.find_by! key: params[:board_id]
  end

  def load_commit
    @commit = @board.commits.find_by! sha: params[:commit_id]
  end
end

app/views/comments/_comment.html.haml
- comment ||= @comment

%li.comment
  = link_to comment.user.github_url, rel: 'new', target: '_blank' do
    = avatar_for comment.user
  .comment-meta
    = link_to comment.user.name, comment.user.github_url, rel: 'new', target: '_blank'
    #{time_ago_in_words comment.updated_at} ago
    = link_to board_commit_comment_path(@board, @commit, comment), class: 'edit-comment', disabled: true do
      edit
  .comment-body{ id: "comment-#{comment.id}" }
    = simple_format emojify(comment.body)
  = render 'comments/form', comment: comment

app/views/comments/_form.html.haml
= form_for [@board, @commit, comment], remote: true do |f|
  = avatar_for current_user if comment.new_record?
  = f.text_area :body, class: 'input-small js-comment-body', placeholder: 'Say what?'
  = f.button 'Cancel', id: 'js-cancel', class: 'btn btn-secondary btn-small' unless comment.new_record?
  = f.submit 'Comment!', class: 'btn btn-primary btn-small'

app/views/comments/create.js.erb
<% if @comment.persisted? %>
  $('.js-card').html('<%= j render('commits/show') %>');
  $('.js-card').trigger('card:initialize');

  $('li[data-commit-sha=<%= @commit.sha %>]').find('.comments-count').text('<%= @commit.comments.count %>');
<% end %>