config/routes.rb
Commitboards::Application.routes.draw do

  post 'oauth/callback'  => 'oauths#callback'
  get  'oauth/callback'  => 'oauths#callback'
  get  'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider
  resource :session , only: [:new, :destroy]
  get 'session/new/:board_id' => 'sessions#new', as: :new_session_from_board

  resource :dashboard, only: :show

  scope :downloads do
    get 'capture'   => 'scripts#capture_script',                     as: 'capture_script'
    get 'bgcapture' => 'scripts#background_capture_script',          as: 'background_capture_script'
    get 'update_and_capture' => 'scripts#update_and_capture_script', as: 'update_and_capture_script'
    get 'imagesnap' => 'scripts#imagesnap',                          as: 'imagesnap'
    get 'version'   => 'scripts#version',                            as: 'version'
  end
  # need an alias for the version checking, since all the distributed scripts have a board url
  get ':board_id/version' => 'scripts#version'

  get 'install/:token' => 'scripts#install', as: 'install'
  # just an alias to the install script as client scripts for commitboards
  # have access to the board url. Then its easy to append /install/<token>
  get ':board_id/install/:token' => 'scripts#install'

  resources :boards, path: '/', only: [:show, :create] do
    resources :commits, only: [:create, :show] do
      resources :comments, only: [:create, :update]
    end
  end

  root 'welcome#index'

end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  skip_before_filter :require_login
  layout false

  def capture_script
    render 'capture.rb.erb'
  end

  def background_capture_script
    render 'background_capture.rb.erb'
  end

  def update_and_capture_script
    render 'update_and_capture.rb.erb'
  end

  def imagesnap
    send_file 'vendor/imagesnap/imagesnap'
  end

  def version
    render text: files_hash
  end

  def install
    @user_board = UserBoardToken.find_by key: params[:token]
    @board = @user_board.board
    render 'project_install.rb.erb', content_type: :text_plain
  end

private
  def files_hash
    scripts = [
      "#{Rails.root}/app/views/scripts/capture.rb.erb",
      "#{Rails.root}/app/views/scripts/background_capture.rb.erb",
      "#{Rails.root}/app/views/scripts/update_and_capture.rb.erb",
      "#{Rails.root}/vendor/imagesnap/imagesnap"]

    md5_for_all = scripts.map { |s| Digest::MD5.file(s).hexdigest }.join('')

    Digest::MD5.hexdigest(md5_for_all)
  end
end

app/views/scripts/_http_proxy_settings_method.rb.erb
#!/usr/bin/env ruby
# find a system proxy is one is set and set curl setting for that proxy
# fallback to no proxy setting if none is found or something goes wrong
def http_proxy_settings
  # this method is slow so lets cache a bit
  return @_http_proxy_settings if @_http_proxy_settings

  network_services_str = `networksetup -listallnetworkservices`
  return '' unless $?.success? # in case command is not available, we fall back to no proxy
  service_names = network_services_str.split("\n")
  service_names.delete_at(0) # first line is not a service name
  service_names.each do |service_name|
    # check if network service is actually enabled before moving on
    next unless `networksetup -showpppoestatus #{shellescape(service_name)}`.strip == 'connected'
    proxy_settings = `networksetup -getwebproxy #{shellescape(service_name)}`
    next unless $?.success?
    next unless proxy_settings.include? 'Enabled: Yes'
    proxy_settings =~ /Server: (.*)\s*Port: (\d*)\s/
    proxy_server = $1
    proxy_port = $2
    return @_http_proxy_settings = "-x #{proxy_server}:#{proxy_port}"
  end
  ''
end

app/views/scripts/_shellescape_method.rb.erb
#!/usr/bin/env ruby

# from http://svn.ruby-lang.org/repos/ruby/trunk/lib/shellwords.rb
def shellescape(str)
  # An empty argument will be skipped, so return empty quotes.
  return "''" if (str.nil? || str.empty?)

  str = str.dup

  # Process as a single byte sequence because not all shell
  # implementations are multibyte aware.
  str.gsub!(/([^A-Za-z0-9_\-.,:\/@\n])/n, "\\\\\\1")

  # A LF cannot be escaped with a backslash because a backslash + LF
  # combo is regarded as line continuation and simply ignored.
  str.gsub!(/\n/, "'\n'")

  return str
end

app/views/scripts/background_capture.rb.erb
#!/usr/bin/env ruby

class BackgroundCapturer

  def initialize
    @home_dir      = File.expand_path('~')
    @update_script = File.join(@home_dir, '.commitboards', 'bin', 'update-and-capture')
    @log_file      = File.join(@home_dir, '.commitboards', 'install.log')
  end

  def run_capture
    info "Capturing and posting to #{ENV['board_url']}"
    system "board_url=#{ENV['board_url']} token=#{ENV['token']} nohup #{@update_script} >> #{@log_file} 2>&1 &"
  end

private
  COLORS = {:default => 9, :red => 31, :yellow => 33, :cyan => 36, :green => 32}
  def info(message)
    msg(message, :cyan)
  end

  def msg(message, color=:default)
    puts "\033[0;#{COLORS[color]};9m#{message}\033[0m"
  end

end

BackgroundCapturer.new.run_capture

app/views/scripts/capture.rb.erb
#!/usr/bin/env ruby

# ruby 1.9 and 2.0 struggles with encoding issues on
# shells that have US-ASCII encoding and not UTF-8.
# The following lines is a fix
if RUBY_VERSION.start_with?('1.9') || RUBY_VERSION.start_with?('2.0')
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end

require 'fileutils'

class Capturer
  def initialize
    @project_dir          = `git rev-parse --show-toplevel 2>&1`.strip
    @project_name         = ENV['project_name'] || @project_dir.split(File::SEPARATOR).last

    @home_dir             = File.expand_path('~')
    @cb_dir               = File.join(@home_dir, '.commitboards')
    @cb_bin_dir           = File.join(@cb_dir, 'bin')
    @imagesnap_executable = File.join(@cb_bin_dir, 'imagesnap')
    @cb_executable        = File.join(@cb_bin_dir, 'capture')
    @cb_projects_dir      = File.join(@cb_dir, 'projects')
    @version_file         = File.join(@cb_bin_dir, 'version')
    @cb_project_dir       = ensure_dir_present(File.join(@cb_projects_dir, @project_name))
    @board_url            = ENV['board_url'] || exit('No board url given')
    @token                = ENV['token']     || exit('No token given')
    @commits_url          = "#{@board_url}/commits"
  end

  def capture
    commit_sha = get_last_commit_sha
    capture_tmp_image(commit_sha)
    upload_success = upload(commit_sha)
    if upload_success
      upload_previous_captures
    end
  end

private

  def version
    File.read(@version_file).strip
  end

  def get_last_commit_sha
    `git rev-parse HEAD`.strip
  end

  def capture_tmp_image(commit_sha)
    inside_dir @cb_project_dir do
      `#{@imagesnap_executable} -q -w 1 #{snapshot_filename(commit_sha)}`
    end
  end

  def upload(commit_sha)
    message = get_commit_message_for(commit_sha)
    commit_timestamp = get_commit_timestamp_for(commit_sha)
    upload_success = post_request(
      :commit_sha   => commit_sha,
      :project_name => @project_name,
      :github_path  => get_github_path,
      :message      => message,
      :timestamp    => commit_timestamp,
      :user_board_token => @token
    )

    clean_uploaded_file(commit_sha) if upload_success

    upload_success
  end

  def get_commit_timestamp_for(commit_sha)
    timestamp_str = `git show -s --format=%ct #{commit_sha}`.strip
  end

  def get_commit_message_for(commit_sha)
    message = `git log --format=%B -n 1 #{commit_sha}`.strip
  end

  def get_github_path
    remotes = `git remote -v`.strip
    return unless remotes =~ /origin\s+(?:git@github\.com:|https:\/\/github\.com\/)(\S+)\.git/
    $1
  end

  def post_request(opts)
    inside_dir @cb_project_dir do
      message          = shellescape opts.fetch(:message)
      project_name     = shellescape opts.fetch(:project_name)
      github_path      = shellescape opts.fetch(:github_path)
      commit_sha       = opts.fetch(:commit_sha)
      timestamp        = opts.fetch(:timestamp)
      user_board_token = shellescape opts.fetch(:user_board_token)
      filename         = shellescape snapshot_filename(commit_sha)

      upload_response = `curl #{http_proxy_settings} #{script_version_header} -s -F commit[user_board_token]=#{user_board_token} -F commit[sha]=#{commit_sha} -F commit[project]=#{project_name} -F commit[github_path]=#{github_path} -F commit[timestamp]=#{timestamp} -F commit[message]=#{message} -F commit[image]=@#{filename} #{@commits_url}`

      if upload_response == 'ok'
        puts "Uploaded #{commit_sha} to #{@commits_url}"
        return true
      else
        puts "Could not upload #{commit_sha} to #{@commits_url} (got code: #{$?} and response: '#{upload_response}')"
        return false
      end
    end
  end

  def script_version_header
    "--header 'X-script-version: #{version}'"
  end

  def upload_previous_captures
    Dir[File.join(@cb_project_dir, '*.jpg')].sort do |f1, f2|
      File.ctime(f1) <=> File.ctime(f2) # sort by date
    end.each do |filename|
      commit_sha = commit_sha_from_filename(filename)
      upload(commit_sha)
    end
  end

  def snapshot_filename(commit_sha)
    "#{commit_sha}.jpg"
  end

  def commit_sha_from_filename(filename)
    filename.match(/([0-9a-f]{40})\.jpg/).captures.first
  end

  def clean_uploaded_file(commit_sha)
    inside_dir @cb_project_dir do
      FileUtils.rm snapshot_filename(commit_sha)
    end
  end

  def ensure_dir_present(path)
    FileUtils.mkdir_p(path) unless File.directory?(path)
    path
  end

  def inside_dir(dirname)
    start_dir = FileUtils.pwd
    FileUtils.cd(dirname)
    begin
      yield
    ensure
      FileUtils.cd(start_dir)
    end
  end

  <%= render 'http_proxy_settings_method.rb.erb' %>
  <%= render 'shellescape_method.rb.erb' %>
end

Capturer.new.capture

app/views/scripts/project_install.rb.erb
#!/usr/bin/env ruby

require 'fileutils'

class Installer
  def install!
    verify_root_of_git_project!
    create_commitboards_directories
    install_or_update_imagesnap
    install_or_update_updater
    install_or_update_background_capture_script
    install_or_update_capture_script
    install_version
    install_post_commit_hook_to_project
    show_success_message
  end

  def verify_root_of_git_project!
    info 'Checking for existence of git project'
    @project_dir = `git rev-parse --show-toplevel 2>&1`.strip
    unless $?.success?
      error('You need to be inside a git project!')
    end
  end

  def create_commitboards_directories
    info "Installing commitboards to #{@project_dir}"
    @home_dir             = ensure_dir_present File.expand_path('~')
    @cb_dir               = ensure_dir_present File.join(@home_dir, '.commitboards')
    @cb_bin_dir           = ensure_dir_present File.join(@cb_dir, 'bin')
    @imagesnap_executable = File.join(@cb_bin_dir, 'imagesnap')
    @cb_executable        = File.join(@cb_bin_dir, 'capture')
    @cb_bg_executable     = File.join(@cb_bin_dir, 'background-capture')
    @cb_update_executable = File.join(@cb_bin_dir, 'update-and-capture')
    @version_file         = File.join(@cb_bin_dir, 'version')
    @cb_projects_dir      = ensure_dir_present File.join(@cb_dir, 'projects')
    # @project_dir is already set
    @project_name         = @project_dir.split(File::SEPARATOR).last
    @post_commit_file     = ensure_file_present File.join(@project_dir, '.git', 'hooks', 'post-commit')
  end

  def install_or_update_imagesnap
    `curl -s #{http_proxy_settings} <%= imagesnap_url %> > #{@imagesnap_executable}`
    FileUtils.chmod(0755, @imagesnap_executable)
  end

  def install_or_update_updater
    `curl -s #{http_proxy_settings} <%= update_and_capture_script_url %> > #{@cb_update_executable}`
    FileUtils.chmod(0755, @cb_update_executable)
  end

  def install_or_update_background_capture_script
    `curl -s #{http_proxy_settings} <%= background_capture_script_url %> > #{@cb_bg_executable}`
    FileUtils.chmod(0755, @cb_bg_executable)
  end

  def install_or_update_capture_script
    `curl -s #{http_proxy_settings} <%= capture_script_url %> > #{@cb_executable}`
    FileUtils.chmod(0755, @cb_executable)
  end

  def install_version
    `curl -s #{http_proxy_settings} <%= version_url %> > #{@version_file}`
  end

  def install_post_commit_hook_to_project
    content = post_commit_content_with_comments

    # Temporary disabling being nice as we want to override the commit hook completely while
    # moving to new key based commit uploads
    #
    # if cb_hook?
    #   warn "Already found a commit hook in '#{@post_commit_file}'."
    #   warn "If you want to add the post-commit command yourself, here it is: #{post_commit_command}"
    #   return
    # end
    #
    # File.open(@post_commit_file, 'a') do |f|
    #   f.write(content)
    #   f.chmod 0755
    # end

    File.open(@post_commit_file, 'w') do |f|
      f.write(content)
      f.chmod 0755
    end

  end

  def show_success_message
    success "\nCongrats! Now go and commit! Then visit your board:"
    success "\n<%= board_url(@board) %>\n"
  end

  def post_commit_content_with_comments
<<-EOS


#{shebang}### commitboards hook (start) ###
#{post_commit_command}
###  commitboards hook (end)  ###
EOS
  end

  def post_commit_command
    "board_url=<%= board_url(@board) %> token=<%= @user_board.key %> #{@cb_bg_executable}"
  end

  def cb_hook?
    File.exists?(@post_commit_file) &&
      File.read(@post_commit_file).to_s =~ /commitboards.*\(start\)(.*\n)*.*commitboards.*\(end\)/
  end

  def shebang
    good_shebang? ? '' : "#!/bin/sh\n\n"
  end

  def good_shebang?
    File.read(@post_commit_file).lines.first =~ /^\#\!\/bin\/.*sh/
  end

private

  def ensure_dir_present(path)
    FileUtils.mkdir_p(path) unless File.directory?(path)
    path
  end

  def ensure_file_present(path)
    dir_path, filename = File.split(path)
    ensure_dir_present(dir_path)
    FileUtils.touch(path)
    path
  end

  COLORS = {:default => 9, :red => 31, :yellow => 33, :cyan => 36, :green => 32}
  def info(message)
    msg(message, :cyan)
  end

  def success(message)
    msg(message, :green)
  end

  def warn(message)
    msg(message, :yellow)
  end

  def error(message)
    msg(message, :red)
    abort('Exiting')
  end

  def msg(message, color=:default)
    puts "\033[0;#{COLORS[color]};9m#{message}\033[0m"
  end
  <%= render 'scripts/http_proxy_settings_method.rb.erb' %>
  <%= render 'scripts/shellescape_method.rb.erb' %>
end

Installer.new().install!

app/views/scripts/update.rb.erb
#!/usr/bin/env ruby

puts 'installing :)'

app/views/scripts/update_and_capture.rb.erb
#!/usr/bin/env ruby

class Updater
  def initialize
    @home_dir           = File.expand_path('~')
    @capture_executable = File.join(@home_dir, '.commitboards', 'bin', 'capture')
    @log_file           = File.join(@home_dir, '.commitboards', 'capture.log')
    @version_file       = File.join(@home_dir, '.commitboards', 'bin', 'version')
    @board_url          = ENV['board_url'] || exit('No board url given')
    @token              = ENV['token']     || exit('No token given')
    @version_url        = "#{@board_url}/version"
    @install_url        = "#{@board_url}/install/#{@token}"
  end

  def run_update_and_capture
    run_update_if_neccessary
    run_capture
  end

  def run_update_if_neccessary
    puts "Checking with server if there is another version.."
    server_version = `curl -s --connect-timeout 2 #{http_proxy_settings} #{@version_url}`.strip
    return unless $?.success? && server_version != local_version
    puts "There is a new version (#{server_version}). Updating before capturing.."
    `curl -s #{http_proxy_settings} #{@install_url} | ruby`
  end

  def run_capture
    puts "Running capture"
    cmd = "token=#{@token} board_url=#{@board_url} #{@capture_executable} >> #{@log_file} 2>&1"
    system(cmd)
  end

  def local_version
    File.read(@version_file).strip
  end

  <%= render 'http_proxy_settings_method.rb.erb' %>
  <%= render 'shellescape_method.rb.erb' %>
end

Updater.new.run_update_and_capture