config/routes.rb
Commitboards::Application.routes.draw do

  post 'oauth/callback'  => 'oauths#callback'
  get  'oauth/callback'  => 'oauths#callback'
  get  'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider
  resource :session , only: [:new, :destroy]
  get 'session/new/:board_id' => 'sessions#new', as: :new_session_from_board

  resource :dashboard, only: :show

  scope :downloads do
    get 'capture'   => 'scripts#capture_script',                     as: 'capture_script'
    get 'bgcapture' => 'scripts#background_capture_script',          as: 'background_capture_script'
    get 'update_and_capture' => 'scripts#update_and_capture_script', as: 'update_and_capture_script'
    get 'imagesnap' => 'scripts#imagesnap',                          as: 'imagesnap'
    get 'version'   => 'scripts#version',                            as: 'version'
  end
  # need an alias for the version checking, since all the distributed scripts have a board url
  get ':board_id/version' => 'scripts#version'

  get 'install/:token' => 'scripts#install', as: 'install'
  # just an alias to the install script as client scripts for commitboards
  # have access to the board url. Then its easy to append /install/<token>
  get ':board_id/install/:token' => 'scripts#install'

  resources :boards, path: '/', only: [:show, :create] do
    resources :commits, only: [:create, :show] do
      resources :comments, only: [:create, :update]
    end
  end

  root 'welcome#index'

end

app/models/board.rb
class Board < ActiveRecord::Base

  has_many :commits, -> { order(committed_at: :desc).includes(:user) }
  belongs_to :owner, class_name: 'User'

  before_validation :generate_key_unless_present
  validates :key, :name, presence: true

  validates :owner_id, presence: true

  def to_param
    key
  end

  def top_committers
    Commit.last_week.
           where(board: self).
           group(:user).
           order('count_id desc').
           limit(3).
           count('id')
  end

private
  def generate_key_unless_present
    self.key = SecureRandom.urlsafe_base64(20) unless key.present?
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_filter :load_board, except: :create
  layout false, only: :incoming

  def show
    unless logged_in?
      flash.alert = "#{view_context.link_to 'Log in', new_session_from_board_path(@board)} to see and make comments!".html_safe
    end
    # same as for CommitsController#show
    @commits = @board.commits.last_week
    @commits_pr_user = @board.top_committers
  end

  def create
    @board = Board.new(board_params.merge(owner: current_user))
    if @board.save
      redirect_to board_url(@board)
    else
      redirect_to root_url
    end
  end

private
  def load_board
    @board = Board.find_by!(key: params[:id])
  end

  def board_params
    params.require(:board).permit(:name)
  end
end

app/views/boards/_board.html.haml
%li
  =link_to board_path(board) do
    #{board.name} with #{board.commits.count} selfies,
    #{current_user.board_commits(board).count} of you

app/views/boards/incoming.html.haml
= render @incoming_commits

app/views/boards/show.html.haml
- title @board.name
= content_for :menu do
  .menu
    %h1= @board.name
    %ul.menu-items
      - if logged_in?
        %li= link_to 'Install', '#', class: 'js-install-link'
        %li= link_to current_user.name, dashboard_path
      - else
        %li= link_to 'Log in to make comments!', new_session_from_board_path(@board)

.center
  - if logged_in?
    %div{id: 'installation-instructions', class: @commits.present? ? 'hidden' : ''}
      .spacing-top.spacing-bottom
        %p Just paste the command below into your shell to install to your project.
        %input{id: 'code-example', class: 'code-example', type: 'text', data: {select_text: true},
          value: "curl #{install_url(UserBoardToken.for(user: current_user, board: @board))} | ruby"}

        %p You can install this commitboard to as many git projects as you like.

  #board.js-live-board{data: {key: @board.key}}

    -# - if @commits_pr_user.present?
    -#   .leaderboard
    -#     %h3 Top committers
    -#     %ol
    -#       - @commits_pr_user.each do |key,value|
    -#         %li= "#{key.name} (#{value})"

    %ul.commits
      = render @commits

-# user is coming directly for a commit from outside the app
- if @commit.present?
  :javascript
    $(window).on('load', function() {
      $('li[data-commit-sha=#{j @commit.sha}] [data-open-card]').trigger('click');
    });


= content_for :bottom do
  .card-overlay.js-card-overlay.js-close-card.hidden
    .card.js-card